name: email_validator
version: 1.0.2

authors: 
  - Fredrik Eilertsen <fredrik.eilertsen@gmail.com>

homepage: https://github.com/fredeil/email-validator.dart
description: A simple (but correct) dart class for validating email addresses
  
environment:
  sdk: '>=1.24.0 <3.0.0'

dev_dependencies:
  test: '1.3.0'
