name: email_validator
version: 3.0.5

homepage: https://github.com/fredeil/email-validator.dart
description: A simple (but correct) dart class for validating email addresses

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  test: ^1.16.8

